<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter" style="float:left;">
    <label class="sorter-label" for="sorter" style="font-weight: bold;"><?php /* @escapeNotVerified */ echo __('SORT BY:') ?></label>
    
    <ul id="sorter" data-role="sorter" class="sorter-options"> 
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <li style="padding-left: 2%;cursor:pointer;color:black;display: inline-block;">
                <a href="#" <?php if ($block->isOrderCurrent($_key)): ?> style="color:orangered !important;" <?php endif; ?>
                >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                    <span style="background: url('pub/media/wysiwyg/select_1.png') 1% no-repeat;width:20px;height:20px;background-size: 50% 40%;display:inline-block;top:.5em;position: relative;"></span>
                </a>
            </li>
            <?php endforeach; ?>
    </ul>
    
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>