<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
	<div class="line"></div>
    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
    <div class="footer-social-icons">
    	<ul class="social-icons">
    		<li><a href="" class="social-icon"> <i class="fa fa-vk"></i></a></li>
    		<li><a href="" class="social-icon"> <i class="fa fa-facebook"></i></a></li>
    		<li><a href="" class="social-icon"> <i class="fa fa-twitter"></i></a></li>
    	</ul>
    </div>
</small>